### ISSUE TITLE
RuntimeError: Stream consumed when reading body with startlette (bug since 1.9.10)

### ISSUE THREAD

**Issue by sevaho** [getsentry/sentry-python#1675]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.10

### Steps to Reproduce

Server:

```python
import sentry_sdk

from fastapi import FastAPI, Request

sentry_sdk.init()

app = FastAPI()


@app.post("/")
async def index(request: Request):
    r = await request.body()
    return {"Hello": "World"}
```

Run with uvicorn:

```
uvicorn app:app --port 5000
```

As client do:

```python
#! /usr/bin/python
import httpx

import asyncio


async def main():
    image = b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\rIDATx\xdac\xfc\xcf\xf0\xbf\x1e\x00\x06\x83\x02\x7f\x94\xad\xd0\xeb\x00\x00\x00\x00IEND\xaeB`\x82"
    files = {"file": ("test.png", image)}
    async with httpx.AsyncClient() as client:
        r = await client.post(
            "http://localhost:5000/",
            files=files,
        )
        print(r)


asyncio.run(main())
```

### Expected Result

To succeed.

### Actual Result

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 293, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 138, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 187, in _run_app
    raise exc from None
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 182, in _run_app
    return await callback()
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 98, in _create_span_call
    await old_call(*args, **kwargs)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 191, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 98, in _create_span_call
    await old_call(*args, **kwargs)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 98, in _create_span_call
    await old_call(*args, **kwargs)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/fastapi.py", line 106, in _sentry_app
    return await old_app(*args, **kwargs)
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sevaho/gitlab/centurion/./app.py", line 14, in read_root
    r = await request.body()
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/requests.py", line 234, in body
    async for chunk in self.stream():
  File "/home/sevaho/.cache/pypoetry/virtualenvs/centurion-X1KYOsH6-py3.10/lib/python3.10/site-packages/starlette/requests.py", line 215, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed

**Comment by antonpirker** [comment]
Hey @sevaho 

Thanks for reporting this. We will have a look when there is time. (Honestly I thought I have fixed this already...)

**Comment by sevaho** [comment]
Thanks @antonpirker !

Looks like there is more to it as well.

```
@app.post("/")
async def index(request: Request, file: UploadFile = File(...)):
    print(file.filename)
    f = await file.read()
    print(f)
    return ""
```

Whatever file you pass, the content for `await file.read()` is always empty due to sentry-sdk absorbing it?

**Comment by mociepka** [comment]
I am facing the same issue in one of the projects I am involved. I can share just traceback:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1870738/197053213-5021833e-deea-41cd-91b7-71798b104cc7.png">

If you need more details, I am happy to help.

**Comment by mecampbellsoup** [comment]
Downgrading to `~1.8` for the time being. Saw this bug on version `1.10.1`.

**Comment by ranjith19** [comment]
I had about 30k errors caused by this since yesterday and I was off. Downgraded the library once I figured this out. Lost a lot of API calls.

**Comment by antonpirker** [comment]
Hello! I will have a look at this first thing on Monday!

**Comment by antonpirker** [comment]
I was (unplanned so) afk Monday and Tuesday, so I am looking into this now.

**Comment by antonpirker** [comment]
This is happening because of some inconsistencies on how Starlette (the foundation of FastAPI) is dealing with request data: 

I am now investigating if this should be fixed in Starlette/FastAPI or in Sentry:
https://github.com/encode/starlette/discussions/1933

**Comment by vduseev** [comment]
Spent a couple of hours debugging this issue until stumbling upon this ticket. Had zero suspicion that it's Sentry causing it. Turns our the only way to get around it is to downgrade FastAPI or to turn off Sentry.

Here is the piece of code causing this issue:

```python
@app.post(
    "/html",
)
async def post_html_resource(
    request: Request,
):
    data = await request.body()
```

Where `app` is a FastAPI class instance and the request is supposed to accept a string as a body. Sentry is initialized before the `app` instance.

![image](https://user-images.githubusercontent.com/23616172/200968471-1a51e42e-e09f-4c87-90f3-934b909765a7.png)

**Comment by hasier** [comment]
I think this issue can be marked as solved, as it's been fixed in version [1.11.0](https://github.com/getsentry/sentry-python/releases/tag/1.11.0) (it's working for me at least). Thanks for your work @antonpirker! 🙇

**Comment by br-allstreet** [comment]
Yeah I am seeing this as well in v1.11.1

**Comment by ibrarrazzaque** [comment]
I got this issue when reading the Query parameters before reading the file. 
Once I read the file and then I could read the other values passed. It seems that once any other part of the incoming request is read before the file/body it can not be access.

**Comment by Sebadst** [comment]
having the issue as well in v1.13.0 . Can we please consider re-opening it?

**Comment by ranjith19** [comment]
Is this fixed in v1.19.x?

**Comment by DAMACANER** [comment]
I am still seeing this issue when I try to manually parse the file by myself https://stackoverflow.com/questions/73442335/how-to-upload-a-large-file-%e2%89%a53gb-to-fastapi-backend

no this isn't fixed in any of the versions. and no, this is not related to the Sentry lib, cause I didn't even hear this library before googling, it is still an issue with Starlette that is ignored, just like many other issues it is thrown to the backlog.

**Comment by smzelek** [comment]
Seeing this in 1.25.1 and not really understanding the circumstances that cause it. Anyone got a useful link?

**Comment by acnebs** [comment]
To everyone commenting that this is still broken, please ensure you are not using any other middlewares, as it is not just Sentry that would cause this issue. Any middleware which reads from the request's `form()` method is going to break if that result is not cached. Realistically this is a bug / design flaw with Starlette/FastAPI that should be fixed on that end.

@caner-cetin if you are not even using this library, then this is definitely not the place you should be commenting. Try commenting on an existing issue in the Starlette or FastAPI repos, or making your own in those repos.

**Comment by smzelek** [comment]
I wanted to come back here to say that the issue I experienced was actually due to exception handling middleware I wrote that should've checked whether the Request had been disconnected.

FastAPI will catch when the Request stream is disconnected, which eventually gets raised as a `starlette.exceptions.HTTPException`, with an upstream error of `RuntimeError("Stream consumed")`. All CustomRouteHandler style Middlewares will be in the stack trace, even though they have nothing to do with the error.

The solution to this is to check for instances of `starlette.exceptions.HTTPException` and check if the request was disconnected. 

Leaving this example here for posterity, as I imagine lots of other people will get confused seeing sentry in the stacktrace if they do something similar, as this is a common approach to writing a generic FastAPI middleware.

```python
class CustomRouteHandler(APIRoute):
    def get_route_handler(self) -> Callable:
        original_route_handler = super().get_route_handler()

        async def handle_route(request: Request) -> Response:
            try:
                response = await original_route_handler(request)

            except Exception as exc:
                if not await request.is_disconnected():
                    # ... handle non-disconnect errors

                response = ApiErrorResponse(error=ErrorDetails(code=..., message='...'))

            return response
```

**Comment by caner-cetin** [comment]
@acnebs Yep, I am sorry for my needless outrage, problem was in MinIO Python SDK, it was reading the stream and not rewinding after read, leaving me with errors when trying to read the same file after uploading to MinIO.

Sorry again! <3
