### ISSUE TITLE
Django signal instrumentation breaks receiver signatures

### ISSUE THREAD

**Issue by aaronmader** [getsentry/sentry-python#1700]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.9

### Steps to Reproduce

I have my own instrumentation around django signals which was broken by the changes in pull request #1526. (commit 412f824b8b53c444671c81ec8e119eba66308064)

My code wraps the django signal class, and makes use of the `receiver.__name__`. As of sentry version 1.9.9, I receive the wrapper name, rather than the expected receiver method name. 

My code (simplified):
```
class TimedSignal(Signal):
    """ Same as signal, but we report on any slow functions """
    def send(self, sender, **named):
        for receiver in self._live_receivers(sender):
            print("receiver.__qualname__ =", receiver.__qualname__)
            print("receiver.__name__ =", receiver.__name__)
            ... (logic with these values) ...
```

Suggested fix:
The `wrapper` method defined within `sentry_receiver_wrapper` should use builtin [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps), to maintain the signature of the original method. 

For example:
```
from functools import wraps
...
        def sentry_receiver_wrapper(receiver):
            # type: (Callable[..., Any]) -> Callable[..., Any]
            @wraps(receiver)
            def wrapper(*args, **kwargs):
```

### Expected Result

I expect to see information about the original receiver method, for example:
```
receiver.__qualname__ = fetch_driver_change_data
receiver.__name__ = fetch_driver_change_data
```

### Actual Result

Instead, I get information about the sentry wrapper:
```
receiver.__qualname__ = patch_signals.<locals>._sentry_live_receivers.<locals>.sentry_receiver_wrapper.<locals>.wrapper
receiver.__name__ = wrapper
```

**Comment by raphaelm** [comment]
This also just broke our system and I'Ve verified that the suggested fix above works

**Comment by AdriNicolau** [comment]
This is fixed on v1.11.1

**Comment by abhinavsingh** [comment]
We are using `v1.11.1` but still getting `func.__module__ = sentry_sdk.integrations.django.signals_handlers` and `func.__name__ = wrapper`.   Are we missing something here?

**Comment by aaronmader** [comment]
From the commit log it looks like this was fixed on Jan 3rd, and is tagged for 1.13.0. 

https://github.com/getsentry/sentry-python/commit/729204fe98e641e8ee5c1ed36c413bea7be028d5
