### ISSUE TITLE
Replay SDK: Session Replay videos do not show in the UI if tunnelling is enabled based on customer report

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-python#1885]
**Problem:**

A customer has tried Session Replay with tunnelling enabled (to get around ad blockers) and Session Replay videos failed to show up in their UI.

As soon as they disabled tunneling, they were able to see Session Replay videos.  They installed the latest versions of `@sentry/react` and `@sentry/replay`. Also `@sentry/tracing`.

Customer details and code snippets found [here in private Jira ticket](https://getsentry.atlassian.net/browse/FEEDBACK-1694).

**Solution Brainstorm:**

TBD.

**Comment by antonpirker** [comment]
I moved this to the `sentry-python` repo because it has something to do with Python

**Comment by smeubank** [comment]
@bruno-garcia and @jas-kas do we have any insight into how big of an issue this for users?

**Comment by sl0thentr0py** [comment]
fixed example in https://github.com/getsentry/examples/pull/172
can close if client side `Content-Type` is not an issue (don't think it is).

**Comment by billyvg** [comment]
@sl0thentr0py So we're also facing a similar issue with the nextjs example as well (ticket just came in yesterday)

**Comment by sl0thentr0py** [comment]
hmm ok we'll need to turn off [`bodyParser`](https://nextjs.org/docs/api-routes/request-helpers#custom-config) to access the raw stream. I think @lforst will be much quicker at fixing nextjs since I have none of the setup locally.

**Comment by bruno-garcia** [comment]
Fixed through: https://github.com/getsentry/examples/pull/173

Thanks folks!

**Comment by lucasfv-c1** [comment]
Sorry for the late response. We faced higher priorities and stopped working on the Replay feature. It seems that it's out of beta now! hooray!
I'm still having issues tunneling the response through Django REST.
In some requests, this is the `dsn` I'm getting (which ends up raising an error and not sending the request):
```
ParseResultBytes(scheme=b'', netloc=b'', path=b'', params=b'', query=b'', fragment=b'')
```

When trying to extract the `hostname` and `project_id` it gets `None`.

**Comment by lforst** [comment]
@jahusa02 You need to add a body parser that can handle binary data.
